### ISSUE TITLE
大佬能不能整个发癫语录呢

### ISSUE THREAD

**Issue by qjksxy** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#10]
就是类似这种插件，能随机输出发癫文案

**Comment by KafCoppelia** [comment]
你要发哪种类型的癫

**Comment by qjksxy** [comment]
对着某个人物发癫  最好能自动替换人物名
比如这种：
https://gist.github.com/qjksxy/c837aeeccc6f48f409604bafcdef8c13

**Comment by KafCoppelia** [comment]
你这个仿佛是另一个插件，那个枝江发癫语录。不在本插件下的讨论范围。

但是这种插件纯粹就是搜集文案罢了，自己动手做一个吧
