### ISSUE TITLE
关于此插件在 nonebot v2.0.0.rc.1 上无法运行的反馈

### ISSUE THREAD

**Issue by Voice-of-Shadow** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#11]
无法导入 ’State‘
这可能与官方的破坏性变更——移除过时的 State 注入参数有关。

![QQ截图20221008052902](https://user-images.githubusercontent.com/115323324/194659424-f97cbf84-1de7-4e0f-a501-0f18ab521d46.png)
![QQ图片20221008052919](https://user-images.githubusercontent.com/115323324/194659456-fc335fe3-b8d7-4a50-9bae-64ff0ff3c85e.png)

**Comment by Voice-of-Shadow** [comment]
↓
`from nonebot.params import Depends, RegexMatched`
↓
`def get_weekday_cn(state: T_State, arg: str = RegexMatched()):`

**Comment by KafCoppelia** [comment]
感谢提醒，[v0.2.6](https://github.com/MinatoAquaCrews/nonebot_plugin_crazy_thursday/releases/tag/v0.2.6)已适配上游`rc1` #12
