### ISSUE TITLE
怎么实现随机发图或文案，有的图也有意思的怎么实现

### ISSUE THREAD

**Issue by liuzj288** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#15]
![](https://img.nga.178.com/attachments/mon_202210/13/i2Qjlz-7y2hK1fT3cSsg-ez.jpg)

**Comment by KafCoppelia** [comment]
呀咩咯，这样搞太麻烦了，我在插件[今天吃什么](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat)中实现了类似的功能，其实现的代码量很大。KFC这个插件本来就是发发文案的……

**Comment by jcjrobert** [comment]
> 呀咩咯，这样搞太麻烦了，我在插件[今天吃什么](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat)中实现了类似的功能，其实现的代码量很大。KFC这个插件本来就是发发文案的……
可以这样，分为两个类型，text/image
每项有两键type和content，text下直接就是内容，image则改成image文件的名字

**Comment by forchannot** [comment]
> 呀咩咯，这样搞太麻烦了，我在插件[今天吃什么](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat)中实现了类似的功能，其实现的代码量很大。KFC这个插件本来就是发发文案的……

其实可以通过简单的random来实现，定于一个rand=random.random或者numpy.random，这个范围是0-1，当返回值为0-x时候发送图片，当返回值为x-1的时候发送文字，不过图片数量可能不是很多导致容易发重复图片，所以这个方法并不完美，但是可行
