### ISSUE TITLE
成功接收了触发指令，但没有消息发送就停止了？

### ISSUE THREAD

**Issue by yyyhop** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#18]
![%B2EH0(90$U5OU%} R8IWS5](https://user-images.githubusercontent.com/116648878/200154169-df87dd63-baf3-4f20-a251-34af65da7c8c.png)

**Comment by KafCoppelia** [comment]
你这个命令是被`nonebot_plugin_kfcrazy`，不是我这个插件啊

**Comment by zhulinyv** [comment]
> ![%B2EH0(90$U5OU%} R8IWS5](https://user-images.githubusercontent.com/116648878/200154169-df87dd63-baf3-4f20-a251-34af65da7c8c.png)

将 `nonebot_plugin_kfcrazy` 插件中的[第14行和第15行](https://github.com/Kaguya233qwq/nonebot_plugin_kfcrazy/blob/5d75c2532c3d28f0e4fde19c0143c1c4b6b29a83/nonebot_plugin_kfcrazy/__init__.py#L14)注释掉就可以了，这两行没什么用，因为作者没写完......

**Comment by yyyhop** [comment]
谢谢，问题解决了，感谢！

**Comment by yyyhop** [comment]
> > ![%B2EH0(90$U5OU%} R8IWS5](https://user-images.githubusercontent.com/116648878/200154169-df87dd63-baf3-4f20-a251-34af65da7c8c.png)
> 
> 将 `nonebot_plugin_kfcrazy` 插件中的[第14行和第15行](https://github.com/Kaguya233qwq/nonebot_plugin_kfcrazy/blob/5d75c2532c3d28f0e4fde19c0143c1c4b6b29a83/nonebot_plugin_kfcrazy/__init__.py#L14)注释掉就可以了，这两行没什么用，因为作者没写完......

感谢，问题解决了！

**Comment by KafCoppelia** [comment]
额额off-topic了已经……
