### ISSUE TITLE
请求安装指导

### ISSUE THREAD

**Issue by shmilyty** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#2]
~~突然发现自己不是很会安装插件~~

![image](https://user-images.githubusercontent.com/61276699/160040918-98ca7050-ac2a-4a6c-91f0-1802b77e0ee7.png)

这是我的bot.py，下面的`load_from_toml`被注释掉了(如果没有注释，就run不起来)
但当我又加了一个插件后，就无法运行了，具体报错如下：

![image](https://user-images.githubusercontent.com/61276699/160040700-be891502-03dc-48d8-95c2-a75166b5d8bb.png)

![image](https://user-images.githubusercontent.com/61276699/160041244-5b4b62c5-b2b3-498e-9f15-9936c49d2069.png)

我尝试删掉`load_from_toml`的注释，结果会导致另一方面的报错：

![image](https://user-images.githubusercontent.com/61276699/160042311-368bbc9a-7741-4ace-8c37-9569a9f995b1.png)

最后，我尝试把这个插件删掉重装，但是我pip unistall，把bot.py该插件注释掉，toml中该插件删掉后运行会出现一开始的报错。

是我没有删干净？还是说这个错误和贵插件没有关系？

**Comment by KafCoppelia** [comment]
建议使用`toml`管理你的插件，[文档](https://v2.nonebot.dev/docs/tutorial/plugin/load-plugin)不是说的很明白么🤔

**Comment by shmilyty** [comment]
`toml`似乎也会有同样的报错/yun

润了。
