### ISSUE TITLE
[BUG] 两个问题

### ISSUE THREAD

**Issue by lakwsh** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#3]
1. 输入疯狂星期天无法识别
2. 日文文案无法替换时间（始终显示木曜日）

**Comment by lakwsh** [comment]
尝试修了一下，不介意我pull吧、、

**Comment by KafCoppelia** [comment]
`星期天`不行是因为`星期日`可以；日文文案是后面补充的缺失没咋想到；文案多了情况也复杂了，比如有“Thursday”、“疯 狂 星 期 四”（带空格），这些按道理能替换也更好；
pr就靠你了！

**Comment by lakwsh** [comment]
之前已经pr了（Thursday也可以的，把除2改成除3、+1改+2就行），然后版本号还没改，你看之后改一下……？
