### ISSUE TITLE
有个问题想请教一下您

### ISSUE THREAD

**Issue by Winj1e** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#6]
![image](https://user-images.githubusercontent.com/105339518/168455655-dacbf109-e835-4339-85e3-493d46daf324.png)
我想问一下，为什么我的插件安装好了程序也没出错，但为什么发送指令不给回复啊？

**Comment by KafCoppelia** [comment]
嗷，群聊才有用，你可以改命令入口的`GROUP`为`GROUP | PRIVATE`，同时记得导入`PRIVATE`

**Comment by Winj1e** [comment]
![image](https://user-images.githubusercontent.com/105339518/168458861-5c709032-e342-4587-b638-6734beac6102.png)
唔。。现在直接报错了

**Comment by KafCoppelia** [comment]
嗷，`MinatoAquaCrews`的所有插件都是基于你的`COMMAND_START=["/"]`（即命令开头`/`可以省略不写），这个报错是你的`/疯狂星期四`进正则匹配匹配不上导致的，后续版本有机会我加强防范吧

**Comment by KafCoppelia** [comment]
在写毕设不敢分时间来维护😵私密马赛

**Comment by Winj1e** [comment]
好的，感谢您能抽空回答我的问题，也祝您能顺利毕业
