### ISSUE TITLE
触发报错：FileNotFoundError: [Errno 2] No such file or directory: 'post.json\\post.json'

### ISSUE THREAD

**Issue by yukuka520** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#7]
QQ发送 疯狂星期四
bot.py返回 FileNotFoundError: [Errno 2] No such file or directory: 'post.json\\post.json'

**Comment by KafCoppelia** [comment]
你的资源路径是啥，应该是指向你存放这个`post.json`的文件夹即可

**Comment by yukuka520** [comment]
> 

他好像放到了python安装文件夹的插件目录下了
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\site-packages\nonebot_plugin_crazy_thursday\resource

但是我的bot放在了桌面

**Comment by KafCoppelia** [comment]
读取文案的默认路径位于`./resource`下；可在`.env.*`下设置：
``` python
CRAZY_PATH="your-path-to-post.json"
```

**Comment by yukuka520** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'your-path-to-post.json\\post.json'

心在是这样了

**Comment by KafCoppelia** [comment]
不是，你的`post.json`如果位于`C:\Desktop\post.json`，那么你就设置：
``` python
CRAZY_PATH="C:\Desktop"
```

**Comment by yukuka520** [comment]
哦哦，明白了，谢谢大佬
